'use strict';
let currentUser=null, profile={}, phones={}, lastInvoiceId=null, deferredInstall=null, tracking=false;
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const num=v=>Number(String(v||'').replace(/[^\d]/g,''))||0;
const money=n=>`${Number(n||0).toLocaleString('en-US')} د.ع`;
const clean=p=>String(p||'').replace(/[^\d]/g,'');
const now=()=>Date.now();
const uid=()=>currentUser?.uid;
const root=()=>db.ref(`users/${uid()}`);
const phoneIndex=p=>db.ref(`phoneIndex/${clean(p)}`);
const newId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
const invoiceNo=(id,created)=>`AR-${new Date(created||now()).getFullYear().toString().slice(2)}${String(id||'').slice(-5).toUpperCase()}`;
const STATUSES={
  received:{text:'تم الاستلام',emoji:'📥',progress:10,cls:'s-received'},
  waiting_check:{text:'بانتظار الفحص',emoji:'⏳',progress:18,cls:'s-checking'},
  checking:{text:'جاري الفحص',emoji:'🔍',progress:28,cls:'s-checking'},
  waiting_customer:{text:'بانتظار موافقة الزبون',emoji:'📞',progress:38,cls:'s-waiting'},
  waiting_part:{text:'بانتظار قطعة',emoji:'📦',progress:48,cls:'s-part'},
  repairing:{text:'جاري الإصلاح',emoji:'🔧',progress:64,cls:'s-repairing'},
  testing:{text:'الاختبار',emoji:'🧪',progress:82,cls:'s-testing'},
  ready:{text:'جاهز للاستلام',emoji:'✅',progress:95,cls:'s-ready'},
  delivered:{text:'تم التسليم',emoji:'🤝',progress:100,cls:'s-delivered'},
  cancelled:{text:'ملغي',emoji:'❌',progress:0,cls:'s-cancelled'}
};
const oldStatusMap={under:'repairing',done:'ready',delivered:'delivered',rejected:'cancelled',new:'received',inspection:'checking',approval:'waiting_customer',repairing:'repairing',testing:'testing',ready:'ready',completed:'ready',cancelled:'cancelled'};
function toast(m){$('#toast').textContent=m;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),2200)}
function fmt(t){let d=new Date(t||now()),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`}
function daysSince(t){return Math.max(0,Math.floor((now()-(Number(t)||now()))/86400000));}
function statusText(k){return STATUSES[k]?.text||k||'-'}
function buildTimeline(r){let tl=Array.isArray(r.timeline)?r.timeline.slice():[]; if(!tl.length){tl.push({status:r.status||'received',text:statusText(r.status||'received'),at:r.createdAt||now(),note:'تم إنشاء السجل'});} return tl.sort((a,b)=>(a.at||0)-(b.at||0));}
function normalize(id,r){if(!r)return null;let created=typeof r.createdAt==='number'?r.createdAt:(Date.parse(r.createdAt)||now());let price=num(r.price??r.repairPrice),paid=num(r.paid??r.paidAmount),remaining=r.remaining!==undefined?num(r.remaining):Math.max(0,price-paid);let status=oldStatusMap[r.status]||r.status||'received';let timeline=buildTimeline({...r,status,createdAt:created});return{_id:id,clientName:r.clientName||r.customerName||'-',clientPhone:r.clientPhone||r.customerPhone||'',deviceName:r.deviceName||r.deviceModel||r.brand||'هاتف',brand:r.brand||'',imei:r.imei||r.serial||'',color:r.color||'',passcode:r.passcode||'',problem:r.problem||r.fault||'-',diagnosis:r.diagnosis||'',accessories:r.accessories||'',technician:r.technician||'',notes:r.notes||'',price,paid,remaining,status,createdAt:created,createdAtText:r.createdAtText||fmt(created),updatedAt:r.updatedAt||created,timeline};}
function statusOptions(){let html=Object.entries(STATUSES).map(([k,v])=>`<option value="${k}">${v.emoji} ${v.text}</option>`).join('');$('#status').innerHTML=html;$('#filterStatus').innerHTML='<option value="all">كل الحالات</option>'+html;$('#statusChoices').innerHTML=Object.entries(STATUSES).map(([k,v])=>`<button type="button" data-set-status="${k}">${v.emoji}<br>${v.text}</button>`).join('')}
statusOptions();
setInterval(()=>{$('#clockNow')&&($('#clockNow').textContent=new Date().toLocaleString('ar-IQ',{hour:'2-digit',minute:'2-digit',weekday:'long',day:'numeric',month:'long'}))},1000);
setTimeout(()=>$('#splash')?.classList.add('hidden'),650);

const params=new URLSearchParams(location.search); if(params.get('track')){tracking=true;$('#splash').classList.add('hidden');$('#trackView').classList.remove('hidden');loadTrack(params.get('uid'),params.get('id'));}
async function loadTrack(u,id){try{let s=await db.ref(`users/${u}/phones/${id}`).get(); if(!s.exists())s=await db.ref(`users/${u}/repairs/${id}`).get(); if(!s.exists())throw Error();let r=normalize(id,s.val());let st=STATUSES[r.status]||STATUSES.received;$('#trackBox').innerHTML=`<div class="infoBox"><h2>${esc(r.deviceName)}</h2><p>الزبون: ${esc(r.clientName)}</p><p>العطل: ${esc(r.problem)}</p><p>الحالة: <b class="${st.cls}">${st.emoji} ${st.text}</b></p><div class="progress"><i style="width:${st.progress}%"></i></div><p>الباقي: ${money(r.remaining)}</p></div><div class="timelineBox"><h3>سجل الحالة</h3>${timelineHTML(r)}</div>`}catch(e){$('#trackBox').textContent='رابط المتابعة غير صالح';}}

$('#loginTab').onclick=()=>authTab('login'); $('#registerTab').onclick=()=>authTab('register');
function authTab(t){$('#loginTab').classList.toggle('active',t==='login');$('#registerTab').classList.toggle('active',t==='register');$('#loginForm').classList.toggle('hidden',t!=='login');$('#registerForm').classList.toggle('hidden',t!=='register')}
$('#registerForm').onsubmit=async e=>{e.preventDefault();let ownerName=$('#ownerName').value.trim(),shopName=$('#shopName').value.trim(),phone=$('#regPhone').value.trim(),email=$('#regEmail').value.trim(),pass=$('#regPassword').value,pass2=$('#regPassword2').value;if(!ownerName||!shopName||!phone||!email||!pass)return toast('أكمل الحقول');if(pass!==pass2)return toast('كلمة المرور غير متطابقة');try{let c=await auth.createUserWithEmailAndPassword(email,pass);await db.ref(`users/${c.user.uid}/profile`).set({ownerName,shopName,phone,email,address:'',terms:['المحل غير مسؤول عن الأجهزة المتروكة أكثر من 30 يوم بعد الإبلاغ بالجاهزية.','الضمان يشمل العطل الذي تم إصلاحه فقط ولا يشمل سوء الاستخدام.'],createdAt:now()});await phoneIndex(phone).set({uid:c.user.uid,email,phone,shopName});}catch(err){toast('تعذر إنشاء الحساب: '+(err.message||''))}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();let id=$('#loginIdentity').value.trim(),pass=$('#loginPassword').value;if(!id||!pass)return toast('اكتب البيانات');try{let email=id;if(!id.includes('@')){let s=await phoneIndex(id).get();if(!s.exists())throw Error('phone');email=s.val().email;}await auth.signInWithEmailAndPassword(email,pass);}catch(err){toast('بيانات الدخول غير صحيحة')}};
$('#logoutBtn').onclick=()=>auth.signOut();
auth.onAuthStateChanged(u=>{if(tracking)return;currentUser=u;if(u){$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');listen();}else{$('#authView').classList.remove('hidden');$('#appView').classList.add('hidden')}});
function listen(){root().child('profile').on('value',s=>{profile=s.val()||{};applyProfile();fillCompany();renderTerms();});root().child('phones').on('value',s=>{phones={};Object.entries(s.val()||{}).forEach(([id,r])=>phones[id]=normalize(id,r));renderAll();});root().child('repairs').on('value',s=>{Object.entries(s.val()||{}).forEach(([id,r])=>{if(!phones[id])phones[id]=normalize(id,r)});renderAll();});}
function applyProfile(){$('#welcomeShop').textContent=profile.shopName||'سجل صيانة الهواتف';}
function arr(){return Object.values(phones).filter(Boolean).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));}
function renderAll(){renderPhones();renderDash();renderCustomers();renderStats();}
function renderDash(){let a=arr(),total=a.reduce((s,r)=>s+r.price,0),paid=a.reduce((s,r)=>s+r.paid,0),rem=a.reduce((s,r)=>s+r.remaining,0),ready=a.filter(r=>r.status==='ready').length,late=a.filter(r=>!['delivered','cancelled'].includes(r.status)&&daysSince(r.createdAt)>=7).length;$('#dashStats').innerHTML=statCards([['الأجهزة',a.length],['الجاهزة',ready],['المستلم',money(paid)],['الديون',money(rem)]]);let tasks=[];if(late)tasks.push(`🔴 يوجد ${late} جهاز متأخر أكثر من 7 أيام.`);if(ready)tasks.push(`🟡 يوجد ${ready} جهاز جاهز للاستلام، تابع الزبائن واتساب.`);if(rem)tasks.push(`💰 إجمالي الديون الحالية: ${money(rem)}.`);$('#todayTasks').innerHTML=tasks.map(t=>`<div class="alertItem">${t}</div>`).join('')||'<div class="alertItem">🟢 لا توجد تنبيهات مهمة حالياً. الشغل مرتب مثل الساعة السويسرية.</div>';}
function statCards(items){return items.map(([l,v])=>`<div class="statCard"><span>${l}</span><b>${v}</b></div>`).join('')}
function renderPhones(){let q=($('#searchPhone')?.value||'').toLowerCase(),sf=$('#filterStatus')?.value||'all';let list=arr().filter(r=>(sf==='all'||r.status===sf)&&`${r.clientName} ${r.clientPhone} ${r.deviceName} ${r.brand} ${r.imei} ${invoiceNo(r._id,r.createdAt)} ${statusText(r.status)}`.toLowerCase().includes(q));$('#phonesList').innerHTML=list.map(cardHTML).join('')||'<div class="alertItem">لا توجد أجهزة.</div>';}
function cardHTML(r){let st=STATUSES[r.status]||STATUSES.received;return `<article class="phoneCard"><div class="phoneTop"><div><h3>${esc(r.deviceName)}</h3><p>${esc(r.clientName)} - ${esc(r.clientPhone)}</p><span class="badge ${st.cls}">${st.emoji} ${st.text}</span></div><div class="money">${money(r.remaining)}</div></div><p>العطل: ${esc(r.problem)}</p><p>الاستلام: ${esc(r.createdAtText)} · منذ ${daysSince(r.createdAt)} يوم</p><div class="progress"><i style="width:${st.progress}%"></i></div><div class="actions"><button data-details="${r._id}">تفاصيل</button><button data-edit="${r._id}">تعديل</button><button data-status="${r._id}">حالة</button><button data-invoice="${r._id}">فاتورة</button><button data-whatsapp="${r._id}">متابعة</button><button data-delete="${r._id}">حذف</button></div></article>`}
function renderCustomers(){let map={};arr().forEach(r=>{let k=clean(r.clientPhone)||r.clientName;if(!map[k])map[k]={name:r.clientName,phone:r.clientPhone,count:0,paid:0,rem:0,last:0};map[k].count++;map[k].paid+=r.paid;map[k].rem+=r.remaining;map[k].last=Math.max(map[k].last,r.createdAt)});$('#customersList').innerHTML=Object.values(map).map(c=>`<article class="customerCard"><h3>${esc(c.name)}</h3><p>${esc(c.phone)}</p><p>عدد الأجهزة: <b>${c.count}</b></p><p>المدفوع: ${money(c.paid)} · الدين: ${money(c.rem)}</p><p>آخر زيارة: ${fmt(c.last)}</p></article>`).join('')||'<div class="alertItem">لا توجد زبائن.</div>'}
function renderStats(){let a=arr(),paid=a.reduce((s,r)=>s+r.paid,0),rem=a.reduce((s,r)=>s+r.remaining,0),del=a.filter(r=>r.status==='delivered').length,active=a.filter(r=>!['delivered','cancelled'].includes(r.status)).length,avg=a.length?Math.round(a.reduce((s,r)=>s+daysSince(r.createdAt),0)/a.length):0;$('#bigStats').innerHTML=statCards([['كل الأجهزة',a.length],['النشطة',active],['المسلمة',del],['المستلم',money(paid)],['الديون',money(rem)],['متوسط الأيام',avg],['جاهزة',a.filter(r=>r.status==='ready').length],['ملغية',a.filter(r=>r.status==='cancelled').length]])}
$('#searchPhone').oninput=renderPhones; $('#filterStatus').onchange=renderPhones;
$$('[data-page]').forEach(b=>b.onclick=()=>goPage(b.dataset.page)); $('#backBtn').onclick=()=>goPage('homePage');
function goPage(id){$$('.page').forEach(p=>p.classList.remove('show'));$('#'+id).classList.add('show');$('#backBtn').classList.toggle('hidden',id==='homePage');window.scrollTo(0,0)}
$('#addPhoneBtn').onclick=()=>openPhone(); $('#addPhoneBtn2').onclick=()=>openPhone();
function calc(){let price=num($('#repairPrice').value),paid=num($('#paidPrice').value);$('#remainPrice').value=Math.max(0,price-paid)} $('#repairPrice').oninput=calc; $('#paidPrice').oninput=calc;
function openPhone(id=null){$('#phoneForm').reset();$('#editingId').value='';$('#status').value='received';$('#createdAtText').value=fmt(now());$('#phoneModalTitle').textContent='إضافة جهاز';if(id){let r=phones[id];$('#phoneModalTitle').textContent='تعديل جهاز';$('#editingId').value=id;['clientName','clientPhone','deviceName','brand','imei','color','passcode','problem','accessories','notes','createdAtText'].forEach(k=>$('#'+k).value=r[k]||'');$('#repairPrice').value=r.price||'';$('#paidPrice').value=r.paid||'';$('#remainPrice').value=r.remaining||'';$('#status').value=r.status;}$('#phoneModal').classList.remove('hidden')}
$('#phoneForm').onsubmit=async e=>{e.preventDefault();calc();let id=$('#editingId').value||newId(),old=phones[id],created=old?.createdAt||now(),status=$('#status').value;let tl=old?.timeline?old.timeline.slice():[{status:'received',text:'تم الاستلام',at:created,note:'تم استلام الجهاز'}];if(!old||old.status!==status)tl.push({status,text:statusText(status),at:now(),note:'حفظ من النموذج'});let data={clientName:$('#clientName').value.trim(),clientPhone:$('#clientPhone').value.trim(),deviceName:$('#deviceName').value.trim(),brand:$('#brand').value.trim(),imei:$('#imei').value.trim(),color:$('#color').value.trim(),passcode:$('#passcode').value.trim(),problem:$('#problem').value.trim(),accessories:$('#accessories').value.trim(),price:num($('#repairPrice').value),paid:num($('#paidPrice').value),remaining:num($('#remainPrice').value),notes:$('#notes').value.trim(),status,createdAt:created,createdAtText:$('#createdAtText').value.trim()||fmt(created),updatedAt:now(),timeline:tl};if(!data.clientName||!data.deviceName)return toast('اسم الزبون واسم الجهاز مطلوبان');await root().child('phones').child(id).set(data);$('#phoneModal').classList.add('hidden');toast('تم حفظ الجهاز');goPage('phonesPage')};
document.addEventListener('click',async e=>{let t=e.target.closest('button');if(!t)return;if(t.dataset.close)$('#'+t.dataset.close).classList.add('hidden');if(t.dataset.edit)openPhone(t.dataset.edit);if(t.dataset.details)showDetails(t.dataset.details);if(t.dataset.status)openStatus(t.dataset.status);if(t.dataset.invoice)showInvoice(t.dataset.invoice);if(t.dataset.whatsapp)whatsappFollow(t.dataset.whatsapp);if(t.dataset.delete)delPhone(t.dataset.delete);if(t.dataset.setStatus)await setStatus(t.dataset.setStatus);});
function timelineHTML(r){return `<div class="timeline">${buildTimeline(r).map(x=>`<div class="step"><b>${esc(x.text||statusText(x.status))}</b><small>${fmt(x.at)}${x.note?' - '+esc(x.note):''}</small></div>`).join('')}</div>`}
function showDetails(id){let r=phones[id],st=STATUSES[r.status]||STATUSES.received;$('#detailsBox').innerHTML=`<div class="detailsGrid"><div class="infoBox"><h2>${esc(r.deviceName)}</h2>${row('رقم الفاتورة',invoiceNo(id,r.createdAt))+row('الزبون',r.clientName)+row('رقمه',r.clientPhone)+row('الشركة',r.brand)+row('IMEI',r.imei)+row('اللون',r.color)+row('العطل',r.problem)+row('الملحقات',r.accessories)+row('الحالة',`${st.emoji} ${st.text}`)+row('السعر',money(r.price))+row('الواصل',money(r.paid))+row('الباقي',money(r.remaining))+row('ملاحظات',r.notes)}</div><div class="timelineBox"><h3>السجل الزمني</h3>${timelineHTML(r)}</div></div>`;$('#detailsModal').classList.remove('hidden')}
function row(k,v){return `<div class="row"><b>${k}</b><span>${esc(v||'-')}</span></div>`}
function openStatus(id){$('#statusEditingId').value=id;$('#statusNote').value='';$('#statusModal').classList.remove('hidden')}
async function setStatus(status){let id=$('#statusEditingId').value,r=phones[id];if(!id||!r)return;let tl=buildTimeline(r);tl.push({status,text:statusText(status),at:now(),note:$('#statusNote').value.trim()});await root().child('phones').child(id).update({status,updatedAt:now(),timeline:tl});$('#statusModal').classList.add('hidden');toast('تم تغيير الحالة وتسجيل الوقت')}
async function delPhone(id){if(confirm('حذف الجهاز نهائياً؟')){await root().child('phones').child(id).remove();toast('تم الحذف')}}
function trackUrl(id){return `${location.origin}${location.pathname}?track=1&uid=${uid()}&id=${id}`}
function showInvoice(id){let r=phones[id];lastInvoiceId=id;let qr=`https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(trackUrl(id))}`,terms=(profile.terms||[]).map((t,i)=>`<p>${i+1}. ${esc(t)}</p>`).join('')||'<p>لا توجد شروط.</p>';$('#invoicePreview').innerHTML=`<div class="invoice"><div class="invHead"><div><h2>عباس راضي</h2><small>${esc(profile.shopName||'سجل صيانة الهواتف')} · ${esc(profile.phone||'')}</small></div><b>${invoiceNo(id,r.createdAt)}</b></div><div class="invBody"><div class="invBox">${row('الزبون',r.clientName)+row('رقم الهاتف',r.clientPhone)+row('الجهاز',r.deviceName)+row('IMEI',r.imei)+row('العطل',r.problem)+row('الحالة',statusText(r.status))+row('تاريخ الاستلام',r.createdAtText)+row('السعر',money(r.price))+row('الواصل',money(r.paid))+row('الباقي',money(r.remaining))}</div><div class="invBox qr"><img src="${qr}" alt="QR"><p>متابعة حالة الجهاز</p></div></div><div class="invBox invTimeline"><h3>السجل الزمني</h3>${timelineHTML(r)}</div><div class="invBox"><h3>الشروط</h3>${terms}</div></div>`;$('#invoiceModal').classList.remove('hidden')}
$('#printBtn').onclick=()=>setTimeout(()=>window.print(),150); $('#sendInvoiceWhatsapp').onclick=()=>lastInvoiceId&&whatsappInvoice(lastInvoiceId);
function waNum(p){let c=clean(p);if(c.startsWith('0'))c='964'+c.slice(1);return c}
function whatsappFollow(id){let r=phones[id],base=r.status==='ready'?r.timeline.find(x=>x.status==='ready')?.at:r.createdAt,d=daysSince(base);let msg=`السلام عليكم ${r.clientName}\nمعكم عباس راضي - سجل الصيانة.\nجهازكم: ${r.deviceName}\nالحالة الحالية: ${statusText(r.status)}\nمر ${d} يوم على ${r.status==='ready'?'جاهزية الجهاز':'استلام الجهاز'}.\nرقم الفاتورة: ${invoiceNo(id,r.createdAt)}\nرابط المتابعة: ${trackUrl(id)}\nشكراً لكم 🌹`;window.open(`https://wa.me/${waNum(r.clientPhone)}?text=${encodeURIComponent(msg)}`,'_blank')}
function whatsappInvoice(id){let r=phones[id];let msg=`فاتورة صيانة من عباس راضي\nرقم: ${invoiceNo(id,r.createdAt)}\nالجهاز: ${r.deviceName}\nالحالة: ${statusText(r.status)}\nالباقي: ${money(r.remaining)}\nرابط المتابعة: ${trackUrl(id)}`;window.open(`https://wa.me/${waNum(r.clientPhone)}?text=${encodeURIComponent(msg)}`,'_blank')}
$('#openCompanyBtn').onclick=()=>$('#companyModal').classList.remove('hidden');
function fillCompany(){if(!$('#setShop'))return;$('#setShop').value=profile.shopName||'';$('#setOwner').value=profile.ownerName||'';$('#setPhone').value=profile.phone||'';$('#setAddress').value=profile.address||'';}
$('#companyForm').onsubmit=async e=>{e.preventDefault();await root().child('profile').update({shopName:$('#setShop').value.trim(),ownerName:$('#setOwner').value.trim(),phone:$('#setPhone').value.trim(),address:$('#setAddress').value.trim()});$('#companyModal').classList.add('hidden');toast('تم حفظ تفاصيل المحل')};
$('#openTermsBtn').onclick=()=>{$('#termsModal').classList.remove('hidden');renderTerms()};
function renderTerms(){let terms=Array.isArray(profile.terms)?profile.terms:[];$('#termsList').innerHTML=terms.map((t,i)=>`<div class="term"><span>${esc(t)}</span><button data-del-term="${i}" type="button">حذف</button></div>`).join('')||'<div class="alertItem">لا توجد شروط.</div>'}
$('#addTermBtn').onclick=async()=>{let v=$('#newTerm').value.trim();if(!v)return toast('اكتب الشرط');let terms=Array.isArray(profile.terms)?profile.terms.slice():[];terms.push(v);await root().child('profile/terms').set(terms);$('#newTerm').value='';toast('تمت إضافة الشرط')};
document.addEventListener('click',async e=>{let b=e.target.closest('[data-del-term]');if(!b)return;let terms=(profile.terms||[]).slice();terms.splice(Number(b.dataset.delTerm),1);await root().child('profile/terms').set(terms)});
$('#exportBtn').onclick=()=>{let data={profile,phones:arr(),exportedAt:fmt(now())},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='abbas-repairos-backup.json';a.click();URL.revokeObjectURL(a.href)};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast('من المتصفح اختر: إضافة إلى الشاشة الرئيسية')};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=200').catch(()=>{});
